version: '3.8'

services:
  postgres:
    image: joshuasundance/postgis_pgvector:1.0.0
    env_file:
      - .env
    volumes:
      - govgis_nov2023-slim-spatial-server_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]

  postgres-init:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file:
      - .env
    volumes:
      - ./backend:/home/appuser/backend
      - ./govgis-nov2023/:/home/appuser/postgres-init
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /home/appuser/backend
    command: ["python", "load_data.py"]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file:
      - .env
    volumes:
      - ./backend:/home/appuser/backend
      - ./models:/home/appuser/models
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      postgres-init:
        condition: service_completed_successfully
    working_dir: /home/appuser/backend
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]
#    command: ["gunicorn", "app:app"]

  mcp:
    build:
      context: .
      dockerfile: Dockerfile
      target: mcp
    env_file:
      - .env
    volumes:
      - ./backend:/home/appuser/backend
    ports:
      - "${MCP_PORT:-8081}:8081"
    depends_on:
      backend:
        condition: service_started
    working_dir: /home/appuser/backend
    command: ["fastmcp", "run", "--transport", "streamable-http", "--host", "0.0.0.0", "--port", "8081", "--no-banner", "mcp.py"]

  inspector:
    image: ghcr.io/modelcontextprotocol/inspector:latest
    environment:
      - HOST=0.0.0.0
    ports:
      - "6274:6274"
      - "6277:6277"

  pgadmin:
    image: dpage/pgadmin4:7.8
    env_file:
      - .env
    volumes:
      - govgis_nov2023-slim-spatial-server_pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-80}:80"


volumes:
  govgis_nov2023-slim-spatial-server_pgdata:
  govgis_nov2023-slim-spatial-server_pgadmin_data:
